spring.datasource.url=jdbc:oracle:thin:@//127.0.0.1:1521/SPLITZONEDB
spring.datasource.username=splitzone
spring.datasource.password=change_this_dev_password
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.pool-name=splitzone-dev-pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.keepalive-time=300000

spring.liquibase.enabled=true
spring.liquibase.default-schema=SPLITZONE
spring.liquibase.liquibase-schema=SPLITZONE
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
